### ISSUE TITLE
Portions Cut Off during Voxelization 

### ISSUE THREAD

**Issue by mahnoor-fatima-saad** [BrendanParmer/Block-On#12]
Hi 

I was testing out Block-On on multiple .stl models. While it performs well on some of my input data producing amazing voxelized results, for some data, it cuts off regions of the model. Can you please clarify which parameters need to be tweaked or what steps I should take to ensure that it performs well on all input .stl models.

This worked perfectly:
![image](https://user-images.githubusercontent.com/45865489/156512940-6f51f9a4-15d5-4a6c-b4a8-340ec9f66fad.png)

The head of the model was cut off:
![image](https://user-images.githubusercontent.com/45865489/156513041-134d87f5-04d9-427c-91b7-0398d823263b.png)

Thanks

**Comment by BrendanParmer** [comment]
Hello!

It seems like your Levels Visible parameter is set too low. If you want to see the whole model, increase the Levels Visible parameter to whatever you set the Resolution parameter to be.

(Also, if you'd like the blocks to be lined up, be sure to apply any transformations you made to the model, it'll automatically update)

Hope this helps!

**Comment by mahnoor-fatima-saad** [comment]
This solved my problem! Thank you so much. 

Another thing I am stuck on is the colour and texture of the model. When I try to run block-on on .obj files with corresponding .mtl files, the colouring and texture does not transfer over to the voxelized model. 

I tried to perform UV mapping on the voxelized model too but wasn't successful. Could you please guide me through what input format you used in the example given? And how you were able to apply the texture on the voxelized output? Thanks!

**Comment by BrendanParmer** [comment]
Hello again! I've just gotten a chance to work on this now that school's done for the semester. 

This should be resolved in the next release, which will come out fairly soon. There are still a couple features I need to work on before that happens, but materials with image textures are functional in the `v1.1` branch. There's an extra step you need to do in the shader editor to get it working so check out the README on how to do that

**Comment by BrendanParmer** [comment]
Version 1.1 has been released!
